export const images = {
    arrow_left_regular: require('@/src/assets/images/arrow-left-regular.png'),
    arrow_right_regular: require('@/src/assets/images/arrow-right-regular.png'),
    bank_regular: require('@/src/assets/images/bank-regular.png'),
    barcode_regular: require('@/src/assets/images/barcode-regular.png'),
    caret_down_regular: require('@/src/assets/images/caret-down-regular.png'),
    caret_left_regular: require('@/src/assets/images/caret-left-regular.png'),
    caret_right_regular: require('@/src/assets/images/caret-right-regular.png'),
    caret_up_regular: require('@/src/assets/images/caret-up-regular.png'),
    credit_card_regular: require('@/src/assets/images/credit-card-regular.png'),
    eye_regular: require('@/src/assets/images/eye-regular.png'),
    eye_slash: require('@/src/assets/images/eye-slash.png'),
    favicon: require('@/src/assets/images/favicon.png'),
    house_regular: require('@/src/assets/images/house-regular.png'),
    house_bold: require('@/src/assets/images/house-bold.png'),
    icon: require('@/src/assets/images/icon.png'),
    magnifying_glass_regular: require('@/src/assets/images/magnifying-glass-regular.png'),
    money_regular: require('@/src/assets/images/money-regular.png'),
    partial_react_logo: require('@/src/assets/images/partial-react-logo.png'),
    pencil_simple_line_regular: require('@/src/assets/images/pencil-simple-line-regular.png'),
    plus_regular: require('@/src/assets/images/plus-regular.png'),
    power_regular: require('@/src/assets/images/power-regular.png'),
    qr_code_regular: require('@/src/assets/images/qr-code-regular.png'),
    sign_out_regular: require('@/src/assets/images/sign-out-regular.png'),
    sliders_regular: require('@/src/assets/images/sliders-regular.png'),
    tag_bold: require('@/src/assets/images/tag-bold.png'),
    tag_regular: require('@/src/assets/images/tag-regular.png'),
    trash_simple_regular: require('@/src/assets/images/trash-simple-regular.png'),
    whatsapp_logo_fill: require('@/src/assets/images/whatsapp-logo-fill.png'),
    x_circle_fill: require('@/src/assets/images/x-circle-fill.png'),
    x_regular: require('@/src/assets/images/x-regular.png'),
}

export type ImagesTypes = keyof typeof images